image: gitpod/workspace-full-vnc
tasks:
  - before: |
      curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip
      unzip protoc-21.12-linux-x86_64.zip -d $HOME/.local
      export PATH="$PATH:$HOME/.local/bin"
      rm protoc-21.12-linux-x86_64.zip
      curl -LO https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
      sudo dpkg -i dbeaver-ce_latest_amd64.deb
      rm dbeaver-ce_latest_amd64.deb
      cd web 
      yarn
      yarn build
  - init: cargo build
    command: cargo watch -x run
