apiVersion: v1
kind: Service
metadata:
  name: lucle
  labels: {{- include "lucle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcport }}
      targetPort: 3000
      protocol: TCP
      name: grpc
  selector: {{- include "lucle.selectorLabels" . | nindent 4 }}
