name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: cd web && pnpm install
      - name: lint
        run: cd web && pnpm lint
      - name: prettier
        run: cd web && yarn prettier
      - name: Build frontend (js side)
        run: cd web && pnpm build
      - name: fmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build backend (rust side)
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
