name: Build container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: cd web && pnpm install
      - name: Build frontend (js side)
        run: cd web && pnpm build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web
          if-no-files-found: error
          path: web/dist
      
  build_aarch64:
    runs-on: ubuntu-latest
    container: ghcr.io/blackdex/rust-musl:aarch64-musl
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lucle-arm64
          if-no-files-found: error
          path: target/aarch64-unknown-linux-musl/release/lucle

  build_x86_64:
    runs-on: ubuntu-latest
    container: ghcr.io/blackdex/rust-musl:x86_64-musl
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lucle-amd64
          if-no-files-found: error
          path: target/x86_64-unknown-linux-musl/release/lucle
      
  build-container:
    runs-on: ubuntu-22.04
    needs: [build_aarch64, build_x86_64, frontend]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          pattern: lucle-*
      - uses: actions/download-artifact@v5
        with:
          name: web
          path: web/dist
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build container
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: ${{ github.event_name == 'push' && true || false }}
          tags: ludea/lucle:latest
          platforms: linux/amd64, linux/arm64
